name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install nearai flake8 pytest

      - name: Lint with flake8
        run: flake8 .

      - name: Run unit tests
        run: |
          if [ -d tests ]; then pytest --maxfail=1 --disable-warnings -q; else echo "No tests to run"; fi

      - name: Smoke-run Frieda agent
        env:
          NEARAI_AUTH_TOKEN: ${{ secrets.NEARAI_AUTH_TOKEN }}
        run: |
          nearai whoami
          nearai agent run ./agent.py --local --dry-run
